name: Portfolio Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: # to trigger the workflow manually from github action tab

permissions:
  pages: write # to deploy to github pages
  id-token: write # to authenticate with cloud provider

jobs:

  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # get access to your portfolio code via pre built actions
      - name: Checkout the code from github repository
        uses: actions/checkout@v4

      # setup the github pages
      - name: Setup the github pages
        uses: actions/configure-pages@v4

      # static code artifact 
      - name: Upload static file
        uses: actions/upload-pages-artifact@v4
        with:
          path: "."

      - name: Deploy to github pages
        uses: actions/deploy-pages@v5